### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by Devetec** [lisiyao21/AnimeInterp#1]
When can we expect a code release?

**Comment by lisiyao21** [comment]
The code and datasets are under internal review and are expected to be released before May.

**Comment by mjc619** [comment]
👀
![image](https://user-images.githubusercontent.com/8377727/116733772-21b95900-a9b2-11eb-905a-6b6312359db6.png)

**Comment by Devetec** [comment]
It's May, lol

**Comment by oblessnoob** [comment]
> The code and datasets are under internal review and are expected to be released before May.

Maybe you mean before 2077.5.1?

**Comment by mjc619** [comment]
well the may comment was deleted, hopefully softsplat gives good results.
[![](http://img.youtube.com/vi/VIYthyp2lto/0.jpg)](http://www.youtube.com/watch?v=uCGD9dT12C0 "Fleetwood Mac - Little Lies (Official Music Video)")

**Comment by n00mkrad** [comment]
![image](https://user-images.githubusercontent.com/61149547/118352564-73411680-b562-11eb-90ac-79e731b57d7a.png)

Oh wonderful.

Legal problems, or money? Hmmm.

**Comment by lisiyao21** [comment]
Buddies, I've just upload the codes and datas. Sorry for keeping you waiting so long. Wish you have fun on this work.
