### ISSUE TITLE
Visual comparison of different optical flows

### ISSUE THREAD

**Issue by 98mxr** [lisiyao21/AnimeInterp#13]
我对RAFT，官方提供的预计算SGM，以及推理时提供的RFR-RAFT和RFR-SGM做了可视化对比。

两组为test中的Japan_v2_3_160208_s3和Japan_v2_3_168850_s3

根据结果有一些疑问。

在不同光流生成的RFR “微调”后可视化的结果几乎完全一致，考查推理结果的SSIM，区别极其微小（类似raft 0.9544416744599089; SGM 0.955205631167391）。我试图故意输入完全错误的预计算光流，得到的中间帧与正确输入光流区别依旧极小。这似乎与论文中w/o SGM的结果类似。想请问引入预计算光流是为了解决何种问题，日后是否可以抛弃这一部分来使用。

我深知光流估计的好坏不能只从可视图上看出，但是RAFT生成的可视图确实具有更为清晰的边界，是否可以提供绕过RFR光流的选项，方便对比不同原始光流的推理结果差异。

A visual comparison of RAFT, pre-calculated SGM, RFR-RAFT and RFR-SGM.

![Japan_v2_3_168850_s3](https://user-images.githubusercontent.com/82786769/119253920-f824d380-bbe5-11eb-97e5-f42dd59694e7.jpeg)
![Japan_v2_3_160208_s3](https://user-images.githubusercontent.com/82786769/119253930-02df6880-bbe6-11eb-9f13-59e300e60c7a.jpeg)

**Comment by lisiyao21** [comment]
m. 感谢你的评论，稍等马上回复

**Comment by lisiyao21** [comment]
Hi. Thanks for your interest. This issue is answered in #11.
