### ISSUE TITLE
About Eq. 1

### ISSUE THREAD

**Issue by laomao0** [lisiyao21/AnimeInterp#16]
Hi Siyao,
     Why equation 1 could measure the similarities of features.
     It uses min(.) operation, why not L1 difference？
Thanks.

**Comment by laomao0** [comment]
single linkage nearest neighbor?

**Comment by xiaofeng94** [comment]
It calculates the intersection of two normalized vectors as their similarity.
Actually, it's called _Histogram Intersection_ that was presented in the paper, color indexing.

**Comment by laomao0** [comment]
> It calculates the intersection of two normalized vectors as their similarity.
> Actually, it's called _Histogram Intersection_ that was presented in the paper, color indexing.

Thanks for your reply!
