### ISSUE TITLE
about training phase in paper

### ISSUE THREAD

**Issue by tinnunculus** [lisiyao21/AnimeInterp#19]
Hi~ firstly, thanks for your great work.

i have a question about training the models.
in paper, 4.4.Learning session, it is mentioned that after first training phase that only trained RFR network not SGM module, we finetune the whole system(SGM + RFR) ...
when you finetuned the whole system, that included SGM??
i wonder whether the pretrained vgg-19 in SGM was fixed or trained.

**Comment by lisiyao21** [comment]
Thanks for your interests!
No, we didn't train the vgg net since the SGM in this paper is a non-differentiable module. It' based on rules.

(That is a good point to improve.)
