### ISSUE TITLE
can not download atd12k

### ISSUE THREAD

**Issue by coolKeen** [lisiyao21/AnimeInterp#23]
Hi, thanks for your nice job!
The download link of atd12k seems to be invalid. Could you please provide another download link?

**Comment by lisiyao21** [comment]
> Hi, thanks for your nice job! The download link of atd12k seems to be invalid. Could you please provide another download link?

Thanks for indicating this! The server we used is down. We will find substitution in one or two days.

**Comment by lisiyao21** [comment]
> Hi, thanks for your nice job! The download link of atd12k seems to be invalid. Could you please provide another download link?

Hi. I've updated the link to Google Drive. Would you please try again?

**Comment by littlewhitesea** [comment]
HI, the updated link to Google Drive also seems to be invalid.

![temp](https://user-images.githubusercontent.com/47802308/142332919-7ed1748e-3f4c-49ce-a391-a372d4a24244.png)

**Comment by lisiyao21** [comment]
> HI, the updated link to Google Drive also seems to be invalid.
> 
> ![temp](https://user-images.githubusercontent.com/47802308/142332919-7ed1748e-3f4c-49ce-a391-a372d4a24244.png)

Hmmm... It is wired. I just tried it one minute ago and it could work...
Try again. If it still doesn't work, please contact me.

**Comment by littlewhitesea** [comment]
Thanks for your reply. The link is valid now.

**Comment by littlewhitesea** [comment]
Thanks for your reply. The link is valid now.
