### ISSUE TITLE
Depth sbtraction

### ISSUE THREAD

**Issue by semel1** [lisiyao21/AnimeInterp#3]
In the images you posted, there small icons on the left upper corner in pink color showing kind of depth map of the reference frame.
Will your upcoming codes allow to output not only interpolated sequence, but corresponded depth maps as well separately?
Such option could be extremely useful for 2D to 3D conversion, especially for animation.

**Comment by 98mxr** [comment]
I think that is not a depth map but a flow map

Please correct me if there is an error

**Comment by semel1** [comment]
"I think that is not a depth map but a flow map" - you right. I think that "flow map" could be used as "depth map"  to generate left/right view for stereoscopic. Another potential issue is that "flow map" sequence could be generated for interpolated frames only (IMHO). However that could be possibly solved by further "re-interpolation" of the "flow map" sequence.

**Comment by lisiyao21** [comment]
The left-up corner map is a visualization to "optical flow" which indicates pixel-wise movement between two input frames. Our provided code will store the flow maps along with the interpolated results.
