### ISSUE TITLE
Could I use frames in ATD-12k in my paper？

### ISSUE THREAD

**Issue by YUYING96** [lisiyao21/AnimeInterp#30]
Sincerely thank you for your work!

Since my research is based on the dataset ATD-12k you provided, I would like to use the pictures 
contained in the dataset when writing my postgraduate thesis. I would like to use the images 
contained in the dataset to help illustrate some of my findings, is this allowed?

**Comment by lisiyao21** [comment]
Sure. Of course please.
(Sorry for so late reply)
