### ISSUE TITLE
Cannot download the dataset from Google Drive

### ISSUE THREAD

**Issue by zzh-tech** [lisiyao21/AnimeInterp#31]
I have attempted to download the dataset from various machines and accounts, but I have been unsuccessful in doing so. An error message appears each time I attempt to download it.

Would it be possible for you to please check the Google Drive link or provide a new one?
Thank you!

**Comment by lisiyao21** [comment]
Hi Zhihang!

I've just tried and I can download it... Could you please try again?

**Comment by lisiyao21** [comment]
Or you could email/wechat me to show a suitable sharing way.

**Comment by zzh-tech** [comment]
Hi, thank you for your quick response! The problem appears when downloading over half of the dataset. I am not sure have you downloaded the whole dataset successfully?
My WeChat: zzh-tech
