### ISSUE TITLE
光流的效果看起来不太理想

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [lisiyao21/AnimeInterp#9]
![frame1](https://user-images.githubusercontent.com/68835291/118843269-79d1e400-b8fc-11eb-88fe-77768516d8a4.jpg)
![frame2_F21](https://user-images.githubusercontent.com/68835291/118843313-848c7900-b8fc-11eb-926e-d578b60b4b79.jpg)
![frame2_F12](https://user-images.githubusercontent.com/68835291/118843750-ee0c8780-b8fc-11eb-9932-7c2051440869.jpg)
![frame3](https://user-images.githubusercontent.com/68835291/118843332-89512d00-b8fc-11eb-9921-cc59f76ba824.jpg)

**Comment by lisiyao21** [comment]
我康一康

**Comment by YiWeiHuang-stack** [comment]
我使用的测试代码似乎是错误的，可能使用了pre-computed SGM flows.

**Comment by YiWeiHuang-stack** [comment]
但我使用论文中提及的例子生成的光流图似乎是正确的![frame1.jpg](https://user-images.githubusercontent.com/68835291/118917919-7e31e780-b964-11eb-93c1-00b6c8cb328d.jpg)![frame2_F12.jpg](https://user-images.githubusercontent.com/68835291/118917929-80944180-b964-11eb-9f79-35b3c7a739d7.jpg)![frame2_F21.jpg](https://user-images.githubusercontent.com/68835291/118917933-825e0500-b964-11eb-8e88-6bbec3a10b8b.jpg)![frame3.jpg](https://user-images.githubusercontent.com/68835291/118917938-838f3200-b964-11eb-87d2-cd8e5d30d52f.jpg)

**Comment by lisiyao21** [comment]
This issue seems to be talked in other branches, so I closed it.
